Rails.application.routes.draw do
  
  resources :users
  resources :playlists do
    resources :songs, only: [:new, :create, :show, :destroy]
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
  end
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  
  # RESTful Routes (generated by scaffold)

  #Sessions routes (see /controllers/sessions_controller.rb)
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #Follow / Unfollow a Playlist
  post '/follow_playlist/:user_id/:playlist_id', to: 'followings#follow_playlist'
  delete '/unfollow_playlist/:user_id/:playlist_id', to: 'followings#unfollow_playlist'
end
